

package com.github.yinzhouzhou.sdn.grpc.example.api;

import com.github.yinzhouzhou.sdn.grpc.client.api.device.DeviceId;
import com.google.common.annotations.Beta;

/**
 * Information about an event generated by a gNMI device .
 */
@Beta
public interface GnmiEventSubject {

    /**
     * Returns the deviceId associated to this subject.
     *
     * @return the device ID
     */
    DeviceId deviceId();
}
